import uuid
from typing import List

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.enums.audit_action import AuditActionEnum
from app.models.audit_log import AuditLog
from app.repositories.base import BaseRepository


class AuditLogRepository(BaseRepository[AuditLog]):
    """Repository handling platform operations audit trails logs."""

    def __init__(self, db: AsyncSession) -> None:
        super().__init__(AuditLog, db)

    async def get_by_user(self, user_id: uuid.UUID, *, skip: int = 0, limit: int = 100) -> List[AuditLog]:
        """Queries audit log records generated by a specific user."""
        stmt = (
            select(self.model)
            .where(self.model.user_id == user_id)
            .order_by(self.model.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        result = await self.db.execute(stmt)
        return list(result.scalars().all())

    async def get_by_action(self, action: AuditActionEnum, *, skip: int = 0, limit: int = 100) -> List[AuditLog]:
        """Queries audit logs matched by action codes."""
        stmt = (
            select(self.model)
            .where(self.model.action == action)
            .order_by(self.model.created_at.desc())
            .offset(skip)
            .limit(limit)
        )
        result = await self.db.execute(stmt)
        return list(result.scalars().all())
