from enum import Enum


class AuditActionEnum(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    FAILED_LOGIN = "FAILED_LOGIN"
    TOKEN_REFRESH = "TOKEN_REFRESH"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DEACTIVATED = "USER_DEACTIVATED"
    DATASET_UPLOADED = "DATASET_UPLOADED"
    DATASET_ARCHIVED = "DATASET_ARCHIVED"
    SCHEMA_MAPPING_CONFIRMED = "SCHEMA_MAPPING_CONFIRMED"
    VALIDATION_RUN = "VALIDATION_RUN"
    PROFILING_RUN = "PROFILING_RUN"
    ANALYTICS_GENERATED = "ANALYTICS_GENERATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    DOCUMENT_ANALYZED = "DOCUMENT_ANALYZED"
    AI_INSIGHT_GENERATED = "AI_INSIGHT_GENERATED"
    REPORT_GENERATED = "REPORT_GENERATED"
    REPORT_DOWNLOADED = "REPORT_DOWNLOADED"
    SETTINGS_UPDATED = "SETTINGS_UPDATED"
    UNAUTHORIZED_ACCESS_ATTEMPT = "UNAUTHORIZED_ACCESS_ATTEMPT"
