from enum import Enum


class ReportTypeEnum(str, Enum):
    CREDIT_RISK_REPORT = "CREDIT_RISK_REPORT"
    PORTFOLIO_REPORT = "PORTFOLIO_REPORT"
    DATA_QUALITY_REPORT = "DATA_QUALITY_REPORT"
    DIAGNOSTIC_ANALYTICS_REPORT = "DIAGNOSTIC_ANALYTICS_REPORT"
    DOCUMENT_ANALYSIS_REPORT = "DOCUMENT_ANALYSIS_REPORT"
    EXECUTIVE_SUMMARY_REPORT = "EXECUTIVE_SUMMARY_REPORT"
