import React from 'react';
import { useQuery } from '@tanstack/react-query';
import apiClient from '@/lib/api-client';
import { FileText, Download, Calendar, User, FileType } from 'lucide-react';

export const ReportRegistry = () => {
  // Fetch Reports Registry
  const { data, isLoading, error } = useQuery({
    queryKey: ['admin-reports'],
    queryFn: async () => {
      const res = await apiClient.get('/admin/reports');
      return res.data;
    },
  });

  const getFormatBadge = (format: string) => {
    const uppercase = format?.toUpperCase();
    if (uppercase === 'PDF') {
      return 'bg-red-500/10 text-red-500 border-red-500/20';
    }
    if (uppercase === 'XLSX') {
      return 'bg-green-500/10 text-green-500 border-green-500/20';
    }
    return 'bg-slate-500/10 text-slate-500 border-slate-500/20';
  };

  const handleDownload = (reportId: string) => {
    // Navigate directly to download endpoint
    window.open(`/api/v1/reports/${reportId}/download`, '_blank');
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold tracking-tight">Report Document Registry</h2>
        <p className="text-sm text-muted-foreground">Monitor generated compliance assessment reports and output exports.</p>
      </div>

      {error && (
        <div className="rounded border border-destructive/20 bg-destructive/10 p-4 text-destructive">
          Failed to load reports registry.
        </div>
      )}

      {isLoading ? (
        <div className="flex h-32 items-center justify-center">
          <div className="h-6 w-6 animate-spin rounded-full border-2 border-primary border-t-transparent" />
        </div>
      ) : (
        <div className="overflow-x-auto rounded-lg border border-border bg-card shadow-sm">
          <table className="w-full text-left border-collapse" aria-label="Report Registry">
            <thead>
              <tr className="border-b border-border bg-muted/40 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
                <th className="px-6 py-3">Report Title</th>
                <th className="px-6 py-3">Dataset ID</th>
                <th className="px-6 py-3">Report Type</th>
                <th className="px-6 py-3">Export Format</th>
                <th className="px-6 py-3">Generated By</th>
                <th className="px-6 py-3">Created At</th>
                <th className="px-6 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="text-sm divide-y divide-border">
              {data?.items?.map((report: any) => (
                <tr key={report.id} className="hover:bg-muted/10 transition-colors">
                  <td className="px-6 py-4 font-semibold">
                    <div className="flex items-center gap-2">
                      <FileText className="h-4 w-4 text-primary" />
                      <span>{report.title}</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 font-mono text-xs text-muted-foreground">
                    {report.dataset_id || 'N/A'}
                  </td>
                  <td className="px-6 py-4 text-xs font-mono">{report.report_type}</td>
                  <td className="px-6 py-4">
                    <span className={`inline-flex rounded border px-2 py-0.5 text-xs font-bold ${getFormatBadge(report.export_format)}`}>
                      {report.export_format}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-xs font-mono text-muted-foreground">{report.generated_by}</td>
                  <td className="px-6 py-4 text-xs text-muted-foreground">
                    {new Date(report.created_at).toLocaleString()}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <button
                      onClick={() => handleDownload(report.id)}
                      className="inline-flex items-center gap-1.5 rounded border border-primary/20 text-primary bg-primary/5 px-2.5 py-1.5 text-xs font-semibold hover:bg-primary hover:text-primary-foreground transition-colors"
                    >
                      <Download className="h-3.5 w-3.5" />
                      <span>Download</span>
                    </button>
                  </td>
                </tr>
              ))}
              {data?.items?.length === 0 && (
                <tr>
                  <td colSpan={7} className="text-center py-8 text-muted-foreground">
                    No reports currently registered.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};
export default ReportRegistry;
