# Role Constants
ROLE_ADMIN = "ADMIN"
ROLE_CREDIT_RISK_GOVERNANCE_OFFICER = "CREDIT_RISK_GOVERNANCE_OFFICER"
ALLOWED_ROLES = [ROLE_ADMIN, ROLE_CREDIT_RISK_GOVERNANCE_OFFICER]

# Password Validation Configurations
DEFAULT_PASSWORD_MIN_LENGTH = 12

# File Parsing Configurations
MAX_MB_MULTIPLIER = 1024 * 1024
DEFAULT_MAX_UPLOAD_SIZE_MB = 50

# Rate Limit Config Headers
RATE_LIMIT_HEADER = "X-RateLimit-Limit"
RATE_LIMIT_REMAINING_HEADER = "X-RateLimit-Remaining"
RATE_LIMIT_RESET_HEADER = "X-RateLimit-Reset"
